### ISSUE TITLE
Feature:  BMOD data extractor

### ISSUE THREAD

**Issue by paulmking** [JeffersonLab/japan#108]
**Is your feature request related to a problem? Please describe.**
We want to be able to routinely extract the BMOD data into an independent event-level ROOT tree, so we don't need to keep the full evt trees, but can accumulate the BMOD responses over multiple runs.

**Comment by cameronc137** [comment]
What was the progress on this? I believe @wdconinc said that he's gotten a working copy that allows for evt tree extraction based on ErrorFlag cuts?

**Comment by cameronc137** [comment]
This was moved into the combiner class and relies on the errorflag. 

Wouter's default error flag is 0x5b7e6bff, while the one used by the beam mod analysis script is 0xda7e6bff.

I'm testing a device list now and seeing if the analysis script gets the same results.

**Comment by cameronc137** [comment]
This ultimately worked and was used during CREX. Closing.
