### ISSUE TITLE
Blinder setup for the physics runs

### ISSUE THREAD

**Issue by paulmking** [JeffersonLab/japan#110]
We will need to define the size of the blinding boxes for the PREX and CREX runs, and make changes to the blinder to be able to change the BB size on a based on a run number (or rely on a hardcoded change at the right moment).

In Qweak, the seed string was provided to the production analyzers through the MySQL DB, so we also need to make changes to get the seed string from a param file.

In Qweak, I used the MySQL DB outputs to monitor the blinder seed used in each analysis job, to check for comm failures during set up.  This happened very rarely.  There is (and will be) a fall-back blinder string in the code, so blinded channels are always blinded, just not always with the "right" blinder.
We'll need tools to easily check the blinder seed and blinder cross checks without the MySQLDB.

**Comment by wdconinc** [comment]
@paulmking see PR #120. Suggest further discussion there.
- First and second paragraph requirements are implemented.
- Third paragraph not implemented yet.
