### ISSUE TITLE
Store means, moments, and errors in burst tree

### ISSUE THREAD

**Issue by paulmking** [JeffersonLab/japan#133]
**Is your feature request related to a problem? Please describe.**
Right now, the burst tree just contains the mean value for each quantity.

**Describe the solution you'd like**
We want to also have the moments, errors, and number of entries stored for each data element in the burst tree.

**Comment by wdconinc** [comment]
In `feature-vqwk-store-moments` we now store hw_sum, hw_sum_m2, hw_sum_err to the burst output tree. The following command works: `build/qwparity -c prex.conf -r 1296 -e :100k --enable-burstsum` and produces the plots below for a featureless bat(t)ery channel on 100k events with default burst length of 240 patterns.

The multiplet yields are:
`mul->Draw("yield_batery6.hw_sum")`
![image](https://user-images.githubusercontent.com/4656391/58907694-c48cce00-86dc-11e9-9cf4-c9265913e034.png)

The burst mean values are:
`burst->Draw("stat_yield_batery6.hw_sum")`
![image](https://user-images.githubusercontent.com/4656391/58907735-dc645200-86dc-11e9-897f-a20aec3407f1.png)

The burst error bars are:
`burst->Draw("stat_yield_batery6.hw_sum_err")`
![image](https://user-images.githubusercontent.com/4656391/58907943-50065f00-86dd-11e9-8905-550911ac2727.png)

We can look at the means and errors:
```
root [9] burst->Scan("stat_yield_batery6.hw_sum:stat_yield_batery6.hw_sum_err")
************************************
*    Row   * stat_yiel * stat_yiel *
************************************
*        0 * 3.968e-05 * 2.563e-06 *
*        1 * 9.353e-05 * 2.928e-06 *
*        2 * 0.0001061 * 3.210e-06 *
*        3 * 0.0001340 * 1.878e-06 *
*        4 * 0.0001795 * 4.209e-06 *
*        5 * 0.0001315 * 3.190e-06 *
*        6 * 0.0001230 * 2.096e-06 *
*        7 * 0.0001172 * 2.223e-06 *
*        8 * 8.451e-05 * 2.146e-06 *
*        9 * 0.0001131 * 1.993e-06 *
*       10 * 0.0001455 * 2.216e-06 *
*       11 * 0.0001407 * 3.046e-06 *
*       12 * 0.0001204 * 3.233e-06 *
*       13 * 0.0001432 * 2.561e-06 *
*       14 * 0.0001453 * 3.995e-06 *
*       15 * 0.0001505 * 2.846e-06 *
*       16 * 0.0001021 * 3.767e-06 *
*       17 * 7.239e-05 * 3.670e-06 *
*       18 * 0.0001034 * 2.658e-06 *
*       19 * 9.990e-05 * 2.142e-06 *
*       20 * 0.0001105 * 2.059e-06 *
*       21 * 6.724e-05 * 2.673e-06 *
*       22 * 8.263e-05 * 2.861e-06 *
*       23 * 8.235e-05 * 1.918e-06 *
*       24 * 0.0002007 * 4.396e-06 *
Type <CR> to continue or q to quit ==> q
************************************
```

We can compare the uncertainty weighted mean of bursts as:
`burst->Draw("stat_yield_batery6.hw_sum","1/stat_yield_batery6.hw_sum_err")`
![image](https://user-images.githubusercontent.com/4656391/58908260-197d1400-86de-11e9-989f-00a7d30e7bb1.png)
This returns the same mean, within uncertainty. It should be exact, but I didn't line up the end of bursts with the number of events, so it's a statistical mismatch.

**Comment by wdconinc** [comment]
@paulmking Any other requests here? Do we want moments for the individual subblocks (easy to implement, but not sure if useful)? Do we even want m2? I think all relevant info is in the err value.

**Comment by wdconinc** [comment]
Also, I apologize for the ugly fix. I didn't want to add another recursive function to everything, so for now we are stuck with having to put "stat_" in front of quantities that will store moments.

**Comment by wdconinc** [comment]
Implemented scalers. Seem to have variation in good event count (num_samples)... correlated with m2.

![image](https://user-images.githubusercontent.com/4656391/58911841-bf348100-86e6-11e9-97a1-f58645c95e0e.png)

**Comment by wdconinc** [comment]
Guess we could make this a bit cleaner with something like the following prefix "asym_|stat" and then lop off the pipe and following tag(s)...

**Comment by wdconinc** [comment]
I think this can be closed @paulmking
