### ISSUE TITLE
Calculate corrected asymmetry mean and error at end of Correlator

### ISSUE THREAD

**Issue by paulmking** [JeffersonLab/japan#134]
**Is your feature request related to a problem? Please describe.**
In order to get a corrected mean and error on one of the dependent variables in the correlation analysis, we currently need to do the second pass analysis, and take the running sum analysis of the corrected variables.
However, at the end of the correlator, we can use the calculated slopes, covariance matrices, and uncorrected means to calculate the mean, RMS, and error on the corrected quantities.

To look at the distribution in deatil, we would still need a second pass, or a ROOT alias to be used on the first-pass tree.

**Describe the solution you'd like**
Use the analytic formulas to get teh corrected values using the uncorrected means, slopes, and covariance matrices.

**Comment by wdconinc** [comment]
I think this may also be a good opportunity to rewrite the `solve` method in 
https://github.com/JeffersonLab/japan/blob/7dd6740ab09ae655792c40731a26ffa9d02ffe3f/Parity/src/LinReg_Bevington_Pebay.cc#L301
using actual matrix multiplication on diagonal Sigma_P, Sigma_Y etc. That will make implementing this request a matter of a few lines. I think just returning a TMatrixT<Double_t> from `LinRegBevPeb::getSigmaP` etc would then only require a single call to that function and the rest reverts to `TMatrixT<Double_t>::Mult` calls.

**Comment by paulmking** [comment]
This was complete in the develop branch by PR #231.
