### ISSUE TITLE
Add  an operator= in QwSubsystemArray

### ISSUE THREAD

**Issue by paulmking** [JeffersonLab/japan#200]
Quoting from the comment on PR #195 

Right now we have a compiler defined operator= for QwSubsystemArray which is unpredictable, at best, and wrong at worst.

**Comment by wdconinc** [comment]
I didn't mean to imply that this was an easy fix for which I have a solution :-) I am not sure if the correct VQwSubsystemParity::operator= will be performed if we just move the QwSubsystemArrayParity::operator= operations to QwSubsystemArry::operator=. I think it should work, but at the very least, if we don't assign the subsystems in QwSubsystemArray::operator=, we should assign the fields that are owned by QwSubsystemArray, not QwSubsystemArrayParity.

**Comment by paulmking** [comment]
I made the assumption that if it was easy or if you had a fix, you would have put it into PR195.  I added this as an "issue" to remember that you'd identified it as an issue, and that we should try to resolve it sometime. :)

We may be able to shift code to the base class, then to have QwSubsystemArrayParity::operator= explicitly call QwSubsystemArray::operator= .  Or maybe

**Comment by wdconinc** [comment]
Closed per #222
