### ISSUE TITLE
QwAlarmDataHandler uses copy of event cut error flag instead of reference

### ISSUE THREAD

**Issue by wdconinc** [JeffersonLab/japan#207]
### Environment: (where does this bug occur, have you tried other environments)
- branch (master for latest released): develop
- revision (HEAD for most recent): HEAD
- OS or system: n/a
- Special ROOT or Geant4 versions? n/a

### Expected Result: (what do you expect when you execute the steps above)
QwAlarmDataHandler must get the updated event cut error flag (i.e. ErrorFlag in the tree) every time it evaluates for alarms.

### Actual Result: (what do you get when you execute the steps above)
However, it just stores a copy of the event cut error flag when doing ConnectChannels. This is not going to cause the value to change in the future. Relevant line:
https://github.com/JeffersonLab/japan/blob/c0f7501e8a1f6d1fce39ae4ce0e8cecd2e746dea/Parity/src/QwAlarmHandler.cc#L183

**Comment by wdconinc** [comment]
Solution unclear at this point. Related to #206

**Comment by wdconinc** [comment]
Solution clear at this point and addressed by combination of #180, #208. Still needs work in QwAlarmDataHandler though.

**Comment by wdconinc** [comment]
Now coming to a develop branch near you: GetEventcutErrorFlag which can be used in any data handler.

**Comment by cameronc137** [comment]
Resolved in #247
