### ISSUE TITLE
Document parameter file naming conventions

### ISSUE THREAD

**Issue by kpaschke** [JeffersonLab/japan#22]

**Comment by cameronc137** [comment]
There are a bunch of .map files added, and edited in commit 035e045bd49064a6cfa4598397db4282b32bd98e. I don't know why those files are named the way they are, and it is probably arbitrary, but looking at the channel names listed in [here](https://github.com/JeffersonLab/japan/blob/master/Parity/prminput/prexinj_beamline.4000-.map) I can begin to explain why the channels' names are the way they are (but the actual mapping of VQweak ADCs and input channel numbers to these specific data channels is determined by what is actually plugged into the DAQ and would need to be verified by looking at the wiring).

While sitting in the MCC I spoke with Michael Merz and he was happy to explain the naming conventions and placements and documentation of the various injector and accelerator signal channels. Specifically there is a tool on the accelerator subnet website https://ced.acc.jlab.org which allows you to search for the information about a channel or beamline element. More useful perhaps is a schematic that lists all of the beamline elements relative to eachother, giving their placement, type, and channel names, among other things [here](http://opsntsrv.acc.jlab.org/ops_docs/online_document_files/MCC_online_files/injector_quick_reference.pdf). 

This is where we should start in terms of trying to identify any elements by the name given. The nomenclature itself is old, but functional, and is fully documented [here](http://opsntsrv.acc.jlab.org/ops_docs/online_document_files/MCC_online_files/CEBAF_nomenclature_Suhring_handout_9-6-07.pdf). And further information can be found [here](http://opsntsrv.acc.jlab.org/ops_docs/MCC_web_interface/index.asp) and [here](https://www.jlab.org/accel/ops/ops.html). One interesting thing to note is that the numbering starts at 0 at the historical injector beginning, and has increased from 0 to 1 and 2 as elements are placed farther upstream from that position; the letter I indicates inside the injector, and the letter L indicates after the first LINAC cryomodule; and the numerical index is a hex code starting at 0 and going to B, where this index refers to how many passes the electrons measured have traveled (obtained from the relative phase of the bunches, meaning one physical BPM sends several signals along different channels).

**JAPAN**
The naming convention used in the files added to JAPAN are just slightly different, trading IPM (Instrument, Position Monitor) for BPM (Beam Position Monitor), and adding more indicative tails (like x and y, and p and m - for plus and minus).

**What next**
This comment is not meant to be the documentation of the naming conventions, but should be used as the starting point for fully documenting the .map files or making decisions about changing the existing naming conventions to anything else.

**Comment by paulmking** [comment]
Thinking about the integrating detectors:  use "detR###" and "detL###" to represent the detectors in the left and right spectrometers.

**Comment by paulmking** [comment]
Each map file and parameter file has a structure like "stem.runrange.extension" or just "stem.extension".  For example, the injector channel map file used for the recent injector tests is "prexinj_beamline.4000-.map", having the run range beginning at run 4000 and continuing open ended.
The runrange is optional, and can either be a single run number ".4000.", and open ended range ".4000-.", or a closed range ".4000-4123.".

**Comment by cameronc137** [comment]
I made another attempt (6180c1c03f19d68bc68ec60bab708858d0315060) at fixing up the names in there, this time following the suggestions in the meeting two weeks ago: https://prex.jlab.org/wiki/index.php/20181024-Analyzer-Mtg

----

Now I'm trying to compile Japan to test these names (is compilation supposed to work?) but I'm getting some issues with the modified ET system not being noticed even though I have redirected the library search to the correct place (~apar/et-12.0/src/libsrc/.Linux-x86_64 or 64-32/)

"[ 96%] Linking CXX executable qwroot
/bin/ld: skipping incompatible /adaqfs/coda/2.6.2/Linux/lib/libet.so when searching for -let
/bin/ld: cannot find -let
collect2: error: ld returned 1 exit status
make[2]: *** [qwroot] Error 1
make[1]: *** [CMakeFiles/qwroot.dir/all] Error 2"

**Comment by cameronc137** [comment]
If I comment out the ET inclusion in CMakeLists.txt then it compiles everything just fine.

----

I've gotten to the point where I am winging it, and executing ./qwparity /adaq2/data1/apar/parit18_4554.dat begins to work, but fails when it can't find qweak_mysql.conf

"Parameter file: ./Parity/prminput/japan.conf
Error: Could not find any parameter file with name qweak_mysql.conf. Parameter file will remain empty."

**Comment by cameronc137** [comment]
I made another commit changing just a few things, and I am still compiling with the online-ET system cut out.

Also, to get it to use the right .conf file and run number use: 
`qwparity --config prexCH.conf -r <runnumber>`

Attached are some plots that I was able to make: 
[BPMA-Raw-XPvsEventNumber.pdf](https://github.com/JeffersonLab/japan/files/2549727/BPMA-Raw-XPvsEventNumber.pdf)
[BPMA-Raw-YvsEventNumber.pdf](https://github.com/JeffersonLab/japan/files/2549728/BPMA-Raw-YvsEventNumber.pdf)
[BPMAy-Raw-vs-BPMAy-Software-correlation.pdf](https://github.com/JeffersonLab/japan/files/2549729/BPMAy-Raw-vs-BPMAy-Software-correlation.pdf)
[BPMAy-vs-BPMBy-Raw-correlation.pdf](https://github.com/JeffersonLab/japan/files/2549730/BPMAy-vs-BPMBy-Raw-correlation.pdf)
[BPMA-YvsX.pdf](https://github.com/JeffersonLab/japan/files/2549731/BPMA-YvsX.pdf)
