### ISSUE TITLE
add HAPPEX ADCs to jaPAN

### ISSUE THREAD

**Issue by cipriangal** [JeffersonLab/japan#24]

**Comment by paulmking** [comment]
@rwmichaels  To add the HAPPEX ADC instrumentation type to the BCM, you ought to be able to modify the "Create" functions in Parity/src/VQwBCM.cc to include the recognition of the new instrumentation module type, add a template instantiation line to the end of Parity/src/QwBCM.cc, and then add the channel definition for the HAPPEX ADC to a new prexinj_beamline.<firstrun>-<lastrun>.map file for the runs in your test.

The new channel ought to then appear in the root tree outputs.

**Comment by paulmking** [comment]
#58 brought the HAPPEX ADC decoding into the develop branch.  There may be more work to do to get meaningful values out of them, but the basic functionality is there and can be improved incrementally as we identify additional issues.

**Comment by cameronc137** [comment]
I have T'd a Cavity BCM's Charge channel (cav4bc - plugged into ADC3, the 4th vqwk ADC, channel 2, the 3rd channel) and also plugged it into channel 3 (the 4th channel, and one at the bottom) of Happex ADC 1 (the second HAPPEX ADC).

When I look at the Cavity BCM's charge I see a very large and railed number in the HAPPEX ADC, but I see normal numbers in the VQWK ADC channel (run 1283 and 1285). I thought maybe this has to do with the sign of voltage input to the module or something along those lines, and so I plugged the 12 bit ADC value from the HAPPEX Timing Board into the same 2 channels in run 1284 (read out in a new map in apar@adaq Parity/prminput/prexCH_beamline.1283-.map, read out as adc18_cav4bc and cav4bc), and with this randomly (event-wise) jumping DAC output (unplugged from scaler synch test and plugged into the two ADCs through the T) I do see a perfect correlation (both examples attached). 

Congrats!! The decoding works in Japan on raw data, at least at a basic level, neglecting pedestals, etc.

[HAPPEX_ADC_Random_DAC12_Works.pdf](https://github.com/JeffersonLab/japan/files/2887600/HAPPEX_ADC_Random_DAC12_Works.pdf)
[HAPPEX_ADC_BCM_Fails.pdf](https://github.com/JeffersonLab/japan/files/2887601/HAPPEX_ADC_BCM_Fails.pdf)

**Comment by wdconinc** [comment]
Or as Bob would say: "good news everyone!" (mostly)

I haven't set kVoltsPerBit yet to the right value for ADC18.

**Comment by rwmichaels** [comment]
If you plug a too-big signal (over 2 Volts, I think) or a negative signal, the ADC18 might rail or saturate.  However, it's also suspicious that you get 3.76 x 10^9.  This device only produces 18 bits (2.6 x 10^5) so

I wonder where that huge number comes from ?  All you did was swap input sources (DAC12 <--> Cavity BCM) and nothing else ?


Dr. Robert Michaels

Staff Scientist, Jefferson Lab

http://userweb.jlab.org/~rom

________________________________

**Comment by wdconinc** [comment]
Error not caught, that value is 0xDFFF,FFFF. I was working on error detection code yesterday but not committed yet.

**Comment by rwmichaels** [comment]
Just a minor correction to what I said.  I believe that depending on the gain settings the HAPPEX ADCs work from 0 to +5 V at 30 Hz, and generally less

of an issue with saturation at higher frequency.  Still not sure what causes what Cameron observed, but I can run my standalone test code on the data

if you tell me what runs to look at.  This will at least tell if the ADCs were misbehaving, plus can give us a benchmark for JAPAN.


Dr. Robert Michaels

Staff Scientist, Jefferson Lab

http://userweb.jlab.org/~rom

________________________________
