### ISSUE TITLE
Stability cut can be wrong with burp cut on the same channel or device

### ISSUE THREAD

**Issue by leafybillow** [JeffersonLab/japan#242]
### Background 
 I was trying to find a stability cut threshold for BPM position.
 Burp cut combined with stability cut mis-identifies and rejects actual good events.
 It is known this can happen in following setting .
 1. Burp cut on BPM wires,eg bpm4aYM and stability cut on derived position bpm4aY
 2. Burp cut and stability cut on the same derived position

### to Reproduce result
./build/qwparity -r 4230 -c prex_prompt.conf -e 700000:1300000

* Testing with run 4230 on BPM 4aY in a demo commit [ee8115b](https://github.com/JeffersonLab/japan/commit/e3bc086550084b49e1bc20c6595856a22ed11768)
with following event cut
  bpmstripline, bpm4a, absy,-10,10,g,37e-3,0.1
* Same effect will happen with  
  bpmstripline, bpm4a, ym,0,50000,g,0,1000  !! Burp cut on individual wire
  bpmstripline, bpm4a, absy,-10,10,g,37e-3  !! Stability cut on derived position

### Observation when this happened
 1. per event processing time goes up to 10 msec, usually is 2 msec , see [log.txt](https://github.com/JeffersonLab/japan/files/3517866/log.txt)
 2. the fGoodEventCounts in QwVQWK_Channel object in fRollingAvg(in QwEventRing) exceeds the ring size ( which is set to 400). See [log.txt](https://github.com/JeffersonLab/japan/files/3517866/log.txt)

 3. it rejects actual good/stable events, see
[screenshot](https://user-images.githubusercontent.com/26907489/63302957-7a16f880-c2ac-11e9-9def-ac28ca17811f.png)
 4. Stability cut alone works well, see 
[screenshot](https://user-images.githubusercontent.com/26907489/63303029-b21e3b80-c2ac-11e9-82de-a690108d0ab6.png)

###  Why this happened (my speculation)  
 1. In QwEventRing::push(), it calls fRollingAvg.AccumulateAllRunningSum(this_event) then CheckBurpCut(). then in QwEventRing::pop(), it calls fRollingAvg.DeaccumulatingRunningSum(this_event).

 2.  QwSubsystemArrayParity::AccumulateAllRunningSum(...), VQwSubsystemArrayParity::AccumulateRunningSum(..), QwBPMStripline::AccumulateRunningSum(...) and QwVQWK_Channel::AccumulateRunningSum(...) 

> https://github.com/JeffersonLab/japan/blob/d428239fc44ca788fae1e4d3ea3d0aeded0d3d04/Analysis/include/QwVQWK_Channel.h#L163

have default ErrorMask=0xFFFFFFF defined in their own header. Same ErrorMask applies for all DeaccumulatingRunningSum(...) methods. 

If no ErrorFlag other than kBeamStabilityError were changed among fEvent_Ring elements in between push() and pop(), and if the same ErrorMask is consistent, fGoodEventCounts should be balanced at fRING_SIZE(400) when RING_READY is true. 

 3. But ...  CheckBurpCut updates fEvent_Ring elements errorflags with kErrorFlag_BurpCut(2^23) which is covered in default ErrorMask. 

In QwVQWK_Channel::AccumulateRunningSum(value, count, ErrorMask), if (value.ErrorFlag & ErrorMask ) is non-zero and count==-1, it will force n2=0 so that DeaccumulatingRunningSum() will not take effect, that is,  M2 contribution from burp cut failed events will stay in rolling sum. If false M2 contribution is large, it will fail following stable events. Also fGoodEventCounts will be overlimit. Effectively, bad statistics get locked in event ring.
> https://github.com/JeffersonLab/japan/blob/d428239fc44ca788fae1e4d3ea3d0aeded0d3d04/Analysis/src/QwVQWK_Channel.cc#L1371-L1378

### Possible Solution
* A simple quick one: Promote kErrorFlag_BurpCut(2^23) to higher available bit, e.g.(2^29) to skip ErrorMask(0xFFFFFFF = 2^28 -1)  tested in commit [e3bc086](https://github.com/JeffersonLab/japan/commit/ac33a31718058d1d5bc3f483b36cc9945f09229f)
Testing result see
![screenshot](https://user-images.githubusercontent.com/26907489/63303145-eeea3280-c2ac-11e9-8008-8b0ece70d086.png)
 * or CheckBurpCut at a different stage 
 * or Give a specific ErrorMask to fRollingAvg.Deaccumulating() to ignore ErrorFlag_BurpCut(2^23) bit

**Comment by paulmking** [comment]
@leafybillow Your proposed solution in commit ac33a31 (shifting the burp cut bit to a higher bit) seems pretty reasonable.  I'm taking a deeper look, but may just accept that.

**Comment by paulmking** [comment]
Resolved in the operations branch by pull request #243.

@leafybillow I had cherry-picked your source file commit from the "demo" branch, but did not include the commit with the demonstration mapfile.  Or did that need to be included in the main development line also?  If not, we could probably delete the "demo" branch now, unless you want to keep it around for cross-checking purposes.

**Comment by leafybillow** [comment]
@paulmking Thanks! The commit in the map file is to reproduce the problem only and should not be included in main analysis. I will delete the demo branch as well.
