### ISSUE TITLE
diff_* variables are not shown in "burst" and "muls" trees

### ISSUE THREAD

**Issue by leafybillow** [JeffersonLab/japan#269]
### Environment: (where does this bug occur, have you tried other environments)
- branch (master for latest released):  operations
- revision (HEAD for most recent): HEAD
- OS or system: Linux
- Special ROOT or Geant4 versions?  

It would be better to have diff_bpms in burst-level and run-level summary tree.

**Comment by leafybillow** [comment]
![Screenshot from 2019-12-16 10-18-10](https://user-images.githubusercontent.com/26907489/70918642-675bc880-1fed-11ea-8299-8ff1169467af.png)
And it turns out, the "asym_bpm" is actually "diff_bpm". Checked with run 5478 , burstCounter=1.

**Comment by paulmking** [comment]
This has been resolved on the develop branch
