### ISSUE TITLE
Burst summary mis-counts patterns in mulc_dit 

### ISSUE THREAD

**Issue by leafybillow** [JeffersonLab/japan#274]
### Environment: (where does this bug occur, have you tried other environments)
- branch (master for latest released): prex_respin1
- revision (HEAD for most recent): HEAD
- OS or system: linux
- Special ROOT or Geant4 versions? 

### Steps to reproduce: (give a step by step account of how to trigger the bug)
1. ./build/qwparity -r 3305 -c prex_prompt.conf 
where a second combiner map for dithering correction is added in datahandler array. 
2. burst_mulc_dit->Scan("dit_asym_usl.hw_sum : dit_asym_usl.num_samples")
3. mulc_dit->Draw("dit_asym_usl","BurstCounter==1 && ErrorFlag==0")

### Expected Result: (what do you expect when you execute the steps above)
We expect number of entries in histogram matches number of samples in burst summary tree. 

### Actual Result: (what do you get when you execute the steps above)
It seems burst summary lost one pattern from the second burst and ones afterwards, while the histogram drawn from mulc_dit tree looks normal. The burst summary for 'mul' and 'mulc' has no such problem. 

![Screenshot from 2020-01-16 10-19-19](https://user-images.githubusercontent.com/26907489/72537706-9498d200-384a-11ea-8d9f-182944f69cb1.png)
Burst summary missing one pattern in the second burst and afterwards. Also central value mismathced with that from histogram draw. 

![Screenshot from 2020-01-16 10-18-04](https://user-images.githubusercontent.com/26907489/72537737-a4181b00-384a-11ea-9457-334783efc963.png)
Histogram drawn from tree looks normal.

**Comment by paulmking** [comment]
@leafybillow Can you check the result of adding a device_error_code test on the dit_asym_usl plot from the tree?  It may be that one of the beamline channels which contributes to dit_asym_usl is not in the global error definition.

**Comment by leafybillow** [comment]
> @leafybillow Can you check the result of adding a device_error_code test on the dit_asym_usl plot from the tree? It may be that one of the beamline channels which contributes to dit_asym_usl is not in the global error definition.
Ok, with device_error_code flag, now the numbers agree with each other.   @paulmking 
And the event cut of this run is defined by prexCH_beamline_eventcuts.2948-.map  where regression/dithering IV channels are not fully included. I think we need to review the event cuts in this run range. @Gongzi-Zhang 

![Screenshot from 2020-01-16 10-39-41](https://user-images.githubusercontent.com/26907489/72539041-b7c48100-384c-11ea-8c97-02c7f34cb446.png)
