### ISSUE TITLE
IHWP slow EPICs variable should be IGL1I00OD16_16 instead of IGL1I00DI24_24M

### ISSUE THREAD

**Issue by cameronc137** [JeffersonLab/japan#275]
Run 5749 got nearly completely wiped out by a blinder error -> IHWP glitch

IHWP slow EPICs variable should be IGL1I00OD16_16 instead of IGL1I00DI24_24M

Because IGL1I00DI24_24M glitches from time to time, we should use the more stable value IGL1I00OD16_16 (0 = out, 1 = in) for IHWP checking.

![image](https://user-images.githubusercontent.com/12798552/72547301-6622f300-385a-11ea-8ae3-c70e260e2d10.png)
![image](https://user-images.githubusercontent.com/12798552/72547241-468bca80-385a-11ea-93a9-4487b4307d7d.png)
![image](https://user-images.githubusercontent.com/12798552/72547205-2eb44680-385a-11ea-9dfe-1a44224414a9.png)

**Comment by cameronc137** [comment]
![image](https://user-images.githubusercontent.com/12798552/72547406-98345500-385a-11ea-9998-4b8dcf4e5528.png)

**Comment by cameronc137** [comment]
Opposite sign convention: 
![image](https://user-images.githubusercontent.com/12798552/72547810-5bb52900-385b-11ea-94a4-781b2d6c80c4.png)

**Comment by paulmking** [comment]
Can we identify how much this has happened so far?

Are we sure the variable is present in the EPICS events through all of CREX?  Are we decoding it into the slow tree yet?

**Comment by cameronc137** [comment]
Yes, this is present for all of CREX. I’ve added the condition to use the other variable if this new one isn’t present.

**Comment by cameronc137** [comment]
I see that for CREX runs it has happened 5 times in production runs. 4 times (5476, 5486, 5639, 5752) were single read errors that only wipe out ~500 multiplets, and this one at run 5749 was the unlucky opposite case where the glitch was in the first event, causing all the others to fail.

**Comment by paulmking** [comment]
FIxed on operations by PR#276.

The fix should be verified to not cause problems on PREX-2 runs.  It should be fine, but lets' check it anyway.

**Comment by paulmking** [comment]
This is fixed in the develop and master branches.
