### ISSUE TITLE
Compilation error on ubuntu 18.10, gcc-8.2.0: overloaded ‘abs(UInt_t)' ambiguous

### ISSUE THREAD

**Issue by wdconinc** [JeffersonLab/japan#34]
```
/home/wdconinc/git/japan/Analysis/src/QwF1TDContainer.cc: In member function ‘Bool_t QwF1TDContainer::CheckDataIntegrity(ROCID_t, UInt_t*, UInt_t)’:
/home/wdconinc/git/japan/Analysis/src/QwF1TDContainer.cc:1612:91: error: call of overloaded ‘abs(UInt_t)’ is ambiguous
      diff_trigger_time = abs( reference_trig_time-fF1TDCDecoder.GetTDCHeaderTriggerTime() );
```

Will fix it myself.

**Comment by wdconinc** [comment]
Of course, what's abs of an unsigned int really trying to achieve?...

**Comment by wdconinc** [comment]
The real question may be: does this do what it is meant to do? I suspect 
```
abs( reference_trig_time-fF1TDCDecoder.GetTDCHeaderTriggerTime() )
```
just treats `reference_trig_time-fF1TDCDecoder.GetTDCHeaderTriggerTime()` as an uint, making the `abs` useless regardless of the values of `reference_trig_time and `fF1TDCDecoder.GetTDCHeaderTriggerTime()`.

**Comment by wdconinc** [comment]
@paulmking Could you give me branch push access to this? I have a bugfix branch I'd like to push.

**Comment by cipriangal** [comment]
try it now

**Comment by wdconinc** [comment]
Fixed in develop.
