### ISSUE TITLE
Enhancement: Enable continuous integration through travis-ci

### ISSUE THREAD

**Issue by wdconinc** [JeffersonLab/japan#39]
In https://github.com/JeffersonLab/japan/tree/travis-ci there is support for travis-ci building of docker images to be hosted at docker hub. This enables both compilation validation, test case validation (not currently), and automatic deployment of a fully running instance of the latest code of each tag and branch in a container. Containers are fully self-contained and come with a fully working copy of the JLab CE.

**Comment by wdconinc** [comment]
Under https://github.com/JeffersonLab/japan/settings/installations admins of this repo should have a way to add "Travis CI" as an "Installed GitHub Apps".

**Comment by wdconinc** [comment]
Nevermind, it seems to have figured out how to test it, https://travis-ci.com/JeffersonLab/japan/builds/91071929

**Comment by wdconinc** [comment]
When we get a non-failing badge here, we can close this issue: ![badge](https://travis-ci.com/JeffersonLab/japan.svg?branch=travis-ci)

**Comment by paulmking** [comment]
Is there a way to define the Travis CI to use cmake (ideally in an out-of-source build directory), or do we need to create a configure script to do it ourselves?

**Comment by wdconinc** [comment]
Travis CI doesn't actually do anything. Everything is done inside the docker container. So, yeah, we use cmake and out of source build there. Basically we just do mkdir build && cmake .. && make && make install to /usr/local/japan/bin, but we could put the build dir anywhere.

- Building inside Travis CI directly: their environment is ubuntu trusty (last with ROOT as part of standard packages) or xenial (which requires pulling in a compiled ROOT from a PPA, likely mine since I don't know of any others).
- Building inside a docker build in Travis CI: doesn't matter what environment Travis CI gives us since we do all the work in the predictable safety of our jlabce container.

**Comment by paulmking** [comment]
@wdconinc What is the "after_success" section of the .travis.yml intended to be doing?
Is that the deployment stage?

It looks like the build itself is working.

**Comment by wdconinc** [comment]
Yeah, I figured it out. The remaining issue on Travis CI was being able to add the docker username and password to the environment variables on GitHub (i.e. my username and password, or someone who is in the jeffersonlab docker hub group). I had added those to my travis-ci.org account, but the CI is running on travis-ci.com (... no sharing of user details).

So, right now it does indeed build the container, and it will be able to push it to docker hub (just did, in fact, https://hub.docker.com/r/jeffersonlab/japan/tags/) but only when it's run by me. I had to use the docker hub credentials stored on my own travis-ci.com account. Another approach (which we use for remoll) is to store the docker hub credentials in the repository settings but that requires repository admin access.

**Comment by wdconinc** [comment]
`after_success` is indeed used for deployment to docker hub.

Technically there's a `deploy` section too, e.g.
```
deploy:
  provider: releases
  api_key:
    secure: Mzvv.......cstNr61w=
  file:
  - tests.pdf
  skip_cleanup: true
  on:
    repo: JeffersonLab/japan
    tags: true
```
but because docker hub deploys are not file-driven, they have to be done in `after_success`. Typically `after_success` would be for running test suites with standard input, which could then be deployed as release output in the `deploy` section.

**Comment by wdconinc** [comment]
Here is the link to the `travis` cli command that stores docker hub credentials with the repository:
 https://docs.travis-ci.com/user/docker/#pushing-a-docker-image-to-a-registry
The docker hub credentials could be anyone's (e.g. mine, yours).

**Comment by wdconinc** [comment]
Actually, maybe there's no difference between remoll and the current solution here. Let's see...

**Comment by wdconinc** [comment]
See PR at https://github.com/JeffersonLab/japan/pull/52. Closing here.
