### ISSUE TITLE
Change file permissions 755-644

### ISSUE THREAD

**Issue by cipriangal** [JeffersonLab/japan#4]
@paulmking : is there a particular reason why we need to keep the source files executable?

**Comment by wdconinc** [comment]
To be executed when it is all quiet in Japan:
```
git update-index --chmod=-x Analysis/*/* Parity/*/*
```

**Comment by paulmking** [comment]
I think this might work (stepping through all files or trying with wildcards):  `git update-index --chmod=-x script.sh`

**Comment by paulmking** [comment]
This should be largely fixed in develop.  We may need to redo the executable bit change as branches get merged back in.
Closing this issue.
