### ISSUE TITLE
Proposed tree names

### ISSUE THREAD

**Issue by paulmking** [JeffersonLab/japan#45]
Slightly related to issues #19 and #22.

The proposal is to rename the trees generated such that the names for each type of tree are shorter.
- Single event tree:  "Mps_Tree" -> "evt"
- Multiplet tree:  "Hel_Tree"  -> "mul"
- Pair tree (built from pairs, no matter the size of the multiplet):  doesn't exist yet -> "pr"
- EPICS and slow controls tree:  "Slow_Tree" - > "slow"
- Burst tree using short intervals; this is more of a test for MOLLER than something PREX needs, but it ought to be something which can just be switched on without much development:  "Burst_Tree" -> "burst"
- Minirun tree; this would likely be implemented using the burst mechanism with a long interval (~5min); probably we'd want to have correlation info put into this tree too:  doesn't exist yet -> "mrun"
-  Corrected trees; a first-pass corrected tree would be associated to an uncorrected tree; the names would be formed by adding a "c" to the end of the uncorrected tree.  If we have several types of corrections, we may need to think about this more:   doesn't exist yet -> "mulc"

**Comment by wdconinc** [comment]
I was wondering if we might want to call burst trees based on the time interval over which they average, e.g. avg10s, avg1m for 10 secs and 1 min.

**Comment by paulmking** [comment]
The short tree names have now been pulled into develop and into master, so this is done.

**Comment by cameronc137** [comment]
The "mps_histo" and "hel_histo" branches or folders of premade histograms are still named under the old convention

**Comment by paulmking** [comment]
Is anyone actually looking at the histograms, or just plotting values from trees?

**Comment by paulmking** [comment]
Yes, we should change the folder names, but maybe we don't need to routinely generate the histograms...

**Comment by wdconinc** [comment]
I think plotting the histograms in panguin instead of looping over tree variables will be a lot faster...

**Comment by paulmking** [comment]
The histogram directories have been renamed on the develop branch.

Closing this issue.
