### ISSUE TITLE
Restrict push access for users "Your Name" on adaq3

### ISSUE THREAD

**Issue by wdconinc** [JeffersonLab/japan#55]
**Is your feature request related to a problem? Please describe.**
It is currently possible to checkout the repository over https (without authentication), commit locally without valid email address, and push to github over https (again without authentication).

**Describe the solution you'd like**
Require users to commit with valid user.name and user.email. Require users to authenticate when pushing.

**Describe alternatives you've considered**
On shared systems we can't set `git config --global user.name`.

**Comment by paulmking** [comment]
I think we had resolved this a while ago, but I hadn't closed it.
