### ISSUE TITLE
Feature Request: Generalize data handler management and combine .map files

### ISSUE THREAD

**Issue by cameronc137** [JeffersonLab/japan#61]
**Is your feature request related to a problem? Please describe.**
There are several data handler derived classes and they use separate .map files. Also this currently hardcodes the list of handlers, so it should be configurable instead.

**Describe the solution you'd like**
Generalize the handling of handlers, and allow for user configuration files to determine which ones are initialized in addition to the parameters that are passed, all in one file.

**Describe alternatives you've considered**
We could leave it as is and just keep track of which ones are hard coded in.

**Additional context**
I will try to attack this, but I may get stumped pretty quickly.

**Comment by paulmking** [comment]
I noticed while explaining this to Cameron that there are some legacy naming issues in these classes where various objects and configuration files are named things like "regression" when none of the existing classes have names like that.
I will put up a patch to fix the naming in the next day or so.

**Comment by cameronc137** [comment]
These objects are also clearly hard coded into several other places, including Parity/main/QwParity.cc and Parity/src/QwHelicityPattern.cc, so generalization will require probably a new fairly broadly scoped object which is capable of creating, deleting, and keeping track of the various data handler instances.

I am trying to keep track of my understanding of how this all works in [the PREX wiki](https://prex.jlab.org/wiki/index.php/JAPAN/Data_Handler)

**Comment by paulmking** [comment]
There is an already existing class "QwCombinerSubsystem" that demonstrates how to use the data handler to act on the event level.

Handling pairs as distinct from full patterns will likely hang within the HelicityPattern class also, but that needs to be developed further (or we define two helicity patterns, one for the full pattern and one for pairs).  Details of how we use DataHandler will depend on how we implement pair analysis.

Your second comment is also true that these example objects are hardcoded in multiple places, but I have ideas of how to implement these more cleanly and we should meet to discuss.

**Comment by paulmking** [comment]
Resolved by pull request #103
