### ISSUE TITLE
Confusing operator precedence in QwEventBuffer

### ISSUE THREAD

**Issue by wdconinc** [JeffersonLab/japan#63]
### Environment: (where does this bug occur, have you tried other environments)
- branch (master for latest released): develop
- revision (HEAD for most recent): HEAD
- OS or system: c++
- Special ROOT or Geant4 versions? 

### Steps to reproduce: (give a step by step account of how to trigger the bug)
The line at https://github.com/JeffersonLab/japan/blob/89aac33123f353a73196857cb289c8bb3b02a7ca/Analysis/src/QwEventBuffer.cc#L818 is
```
(tmpbank)<<32 + fSubbankTag
```
which is identical, given [C++ operator precedence](https://en.cppreference.com/w/cpp/language/operator_precedence), to
```
(tmpbank)<<(32 + fSubbankTag)
```
This is confusing, at best.

### Expected Result: (what do you expect when you execute the steps above)
Does this do the right thing? Maybe. Maybe not. Maybe no one ever noticed...

**Comment by wdconinc** [comment]
Also at https://github.com/JeffersonLab/japan/blob/89aac33123f353a73196857cb289c8bb3b02a7ca/Analysis/src/VQwSubsystem.cc#L332

**Comment by paulmking** [comment]
Resolved on develop by pull #78
