### ISSUE TITLE
Feature Request: Universal channel-wise helicity-agnostic asymmetry noise floor measurements

### ISSUE THREAD

**Issue by cameronc137** [JeffersonLab/japan#65]
**Is your feature request related to a problem? Please describe.**
When doing pedestal studies it is nice to look at the pair-wise asymmetry noise floor. This asymmetry would not related to the helicity pattern, just each neighboring event or some helicity-agnostic patterns to check for line noise or electronic pickups. If we could have it generated for every channel automatically I think that would be nice (as long as this isn't threatening blinding I guess), and then this would be useful as a diagnostic for the health of detector channels during normal running, as well as save time for users doing dedicated pedestal studies.

**Describe the solution you'd like**
Add a new branch to either MPS tree or Hel tree for each regular pattern kind of asymmetry noise floor we can think to calculate

**Describe alternatives you've considered**
I can always just loop over the MPS tree in a macro and take the asymmetry myself, but having this be done in a running sum kind of way would allow for an online analyzer to track this number as well, and if included in the burst tree (this is minute scales right?) would allow for detection of short time scale introduction of noise (especially in detectors like the SAMs or some simple scaler which is supposed to be very stable). I'm probably asking to reinvent the wheel, as this is likely already implemented or there are probably more intelligent ways to monitor noise floors in online analysis, but I think this kind of thing would be nice to look at on various time scales without needing to adapt slower ROOT macros for each feasible application.

**Additional context**
We will need to do battery and empty channel pedestal studies regularly, so including this kind of feature from the ground up will make life easier and hopefully prevent mistakes in hasty analyses later on.

**Comment by paulmking** [comment]
I think this is largely resolved by pull request #96.

We can revisit the goals of this issue after we have some experience with the pair tree.
