### ISSUE TITLE
Feature:  Development of "mini runs"

### ISSUE THREAD

**Issue by paulmking** [JeffersonLab/japan#77]
**Is your feature request related to a problem? Please describe.**
For many time-dependent effects, such as determining correlations, the natural hour-long length of data files is too long.  Also, flagging a full data file as being good/bad/suspect does not give us adequate granularity for flagging problems.

**Describe the solution you'd like**
A software option to enable output of results (in some form) accumulated for a certain number of patterns, forming a "mini-run".  A minirun should have mean, RMS, error, and number of good entries for the yields, asymmetries, and diffs of "all" quantities.  Correlation matrices should also be determined for the minirun.

A minirun which has "too few" events should be combined (or combinable) with an adjacent minirun, so we do not have orphan events.

Should a minirun be a fixed time, or should it be a fixed number of "good events"?

Minirun outputs could go into a special tree, or have the existing trees broken into segments within their ROOT file.

The existing mulitplet tree should have a variable indicating the minirun index for a particular event.

**Describe alternatives you've considered**
We could have CODA break datafiles at much smaller sizes to create file segments that each last ~5 minutes (or however long we want as a minirun).  We'd then analyze each file as an independent unit.  It is less flexible, than using a software minirun length though.

**Comment by wdconinc** [comment]
Today at lunch we talked about three options (at least):
- fixed number of good events per minirun (e.g. 10000 events but could be more than 6 minutes)
- fixed amount of time per minirun (e.g. 6 minutes, but could be only 5000 events)
- changing over at beam trips so some miniruns can be marked as trips while others are between trips (even if some might be only 1 minute long then, in particularly trippy conditions).

**Comment by paulmking** [comment]
In the discussion today, we decided that miniruns should be defined to contain a fixed number of good events.

Note that if we change the event cut definitions, the association of minirun number to pattern number will change.

**Comment by cameronc137** [comment]
Do we have a minirun_number branch available? If not, this would be valuable for post-processing and aggregation (and I'm willing to tackle it, if I can be pointed in the right direction first :) )

**Comment by paulmking** [comment]
In commit 54297bb we now have all the pieces of mini-runs working together.  The runningsums of the datahandler objects are done in a kind of ugly way.

See my comment on commit 54297bb  for a though on how to change it to be simpler.

**Comment by paulmking** [comment]
The minirun framework has been working in the develop (and others) branch for quite some time.  We still could do some refactoring and cleanup work, but that should go in as a new issue.
